// Generated from src/models.ts for compatibility with older running ClawRouter proxies.
// Regenerate whenever the root model catalog changes.
export type BundledModelMetadata = {
  name: string;
  owned_by: string;
  context_window: number;
  max_output: number;
  input_price: number;
  output_price: number;
  reasoning: boolean;
  vision: boolean;
  agentic: boolean;
  tool_calling: boolean;
};

export const BUNDLED_MODEL_METADATA: Record<string, BundledModelMetadata> = {
  auto: {
    name: "Auto (Smart Router - Balanced)",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 128000,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  eco: {
    name: "Eco (Smart Router - Cost Optimized)",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 128000,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  premium: {
    name: "Premium (Smart Router - Best Quality)",
    owned_by: "blockrun",
    context_window: 2000000,
    max_output: 200000,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "openai/gpt-5.2": {
    name: "GPT-5.2",
    owned_by: "openai",
    context_window: 400000,
    max_output: 128000,
    input_price: 1.75,
    output_price: 14,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "openai/gpt-5-mini": {
    name: "GPT-5 Mini",
    owned_by: "openai",
    context_window: 200000,
    max_output: 65536,
    input_price: 0.25,
    output_price: 2,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/gpt-5-nano": {
    name: "GPT-5 Nano",
    owned_by: "openai",
    context_window: 128000,
    max_output: 32768,
    input_price: 0.05,
    output_price: 0.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/gpt-5.2-pro": {
    name: "GPT-5.2 Pro",
    owned_by: "openai",
    context_window: 400000,
    max_output: 128000,
    input_price: 21,
    output_price: 168,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/gpt-5.5": {
    name: "GPT-5.5",
    owned_by: "openai",
    context_window: 1050000,
    max_output: 128000,
    input_price: 5,
    output_price: 30,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "openai/gpt-5.4": {
    name: "GPT-5.4",
    owned_by: "openai",
    context_window: 400000,
    max_output: 128000,
    input_price: 2.5,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "openai/gpt-5.4-mini": {
    name: "GPT-5.4 Mini",
    owned_by: "openai",
    context_window: 400000,
    max_output: 128000,
    input_price: 0.75,
    output_price: 4.5,
    reasoning: false,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "openai/gpt-5.4-pro": {
    name: "GPT-5.4 Pro",
    owned_by: "openai",
    context_window: 400000,
    max_output: 128000,
    input_price: 30,
    output_price: 180,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/gpt-5.4-nano": {
    name: "GPT-5.4 Nano",
    owned_by: "openai",
    context_window: 1050000,
    max_output: 32768,
    input_price: 0.2,
    output_price: 1.25,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/gpt-5.3": {
    name: "GPT-5.3",
    owned_by: "openai",
    context_window: 128000,
    max_output: 16000,
    input_price: 1.75,
    output_price: 14,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "openai/gpt-5.3-codex": {
    name: "GPT-5.3 Codex",
    owned_by: "openai",
    context_window: 400000,
    max_output: 128000,
    input_price: 1.75,
    output_price: 14,
    reasoning: false,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "openai/gpt-4.1": {
    name: "GPT-4.1",
    owned_by: "openai",
    context_window: 128000,
    max_output: 16384,
    input_price: 2,
    output_price: 8,
    reasoning: false,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "openai/gpt-4.1-mini": {
    name: "GPT-4.1 Mini",
    owned_by: "openai",
    context_window: 128000,
    max_output: 16384,
    input_price: 0.4,
    output_price: 1.6,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/gpt-4.1-nano": {
    name: "GPT-4.1 Nano",
    owned_by: "openai",
    context_window: 128000,
    max_output: 16384,
    input_price: 0.1,
    output_price: 0.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/gpt-4o": {
    name: "GPT-4o",
    owned_by: "openai",
    context_window: 128000,
    max_output: 16384,
    input_price: 2.5,
    output_price: 10,
    reasoning: false,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "openai/gpt-4o-mini": {
    name: "GPT-4o Mini",
    owned_by: "openai",
    context_window: 128000,
    max_output: 16384,
    input_price: 0.15,
    output_price: 0.6,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/o1": {
    name: "o1",
    owned_by: "openai",
    context_window: 200000,
    max_output: 100000,
    input_price: 15,
    output_price: 60,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/o3": {
    name: "o3",
    owned_by: "openai",
    context_window: 200000,
    max_output: 100000,
    input_price: 2,
    output_price: 8,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/o3-mini": {
    name: "o3-mini",
    owned_by: "openai",
    context_window: 128000,
    max_output: 65536,
    input_price: 1.1,
    output_price: 4.4,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "openai/o4-mini": {
    name: "o4-mini",
    owned_by: "openai",
    context_window: 128000,
    max_output: 65536,
    input_price: 1.1,
    output_price: 4.4,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "anthropic/claude-haiku-4.5": {
    name: "Claude Haiku 4.5",
    owned_by: "anthropic",
    context_window: 200000,
    max_output: 8192,
    input_price: 1,
    output_price: 5,
    reasoning: false,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "anthropic/claude-sonnet-4.5": {
    name: "Claude Sonnet 4.5",
    owned_by: "anthropic",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "anthropic/claude-sonnet-4.6": {
    name: "Claude Sonnet 4.6",
    owned_by: "anthropic",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "anthropic/claude-opus-4.5": {
    name: "Claude Opus 4.5",
    owned_by: "anthropic",
    context_window: 200000,
    max_output: 32000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "anthropic/claude-opus-4.6": {
    name: "Claude Opus 4.6",
    owned_by: "anthropic",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "anthropic/claude-opus-4.7": {
    name: "Claude Opus 4.7",
    owned_by: "anthropic",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "anthropic/claude-opus-4.8": {
    name: "Claude Opus 4.8",
    owned_by: "anthropic",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "google/gemini-3.1-pro": {
    name: "Gemini 3.1 Pro",
    owned_by: "google",
    context_window: 1050000,
    max_output: 65536,
    input_price: 2,
    output_price: 12,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "google/gemini-3.5-flash": {
    name: "Gemini 3.5 Flash",
    owned_by: "google",
    context_window: 1048576,
    max_output: 65536,
    input_price: 0.5,
    output_price: 3,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "google/gemini-3-flash-preview": {
    name: "Gemini 3 Flash Preview",
    owned_by: "google",
    context_window: 1000000,
    max_output: 65536,
    input_price: 0.5,
    output_price: 3,
    reasoning: false,
    vision: true,
    agentic: false,
    tool_calling: false,
  },
  "google/gemini-2.5-pro": {
    name: "Gemini 2.5 Pro",
    owned_by: "google",
    context_window: 1050000,
    max_output: 65536,
    input_price: 1.25,
    output_price: 10,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "google/gemini-2.5-flash": {
    name: "Gemini 2.5 Flash",
    owned_by: "google",
    context_window: 1000000,
    max_output: 65536,
    input_price: 0.3,
    output_price: 2.5,
    reasoning: false,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "google/gemini-2.5-flash-lite": {
    name: "Gemini 2.5 Flash Lite",
    owned_by: "google",
    context_window: 1000000,
    max_output: 65536,
    input_price: 0.1,
    output_price: 0.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "google/gemini-3.1-flash-lite": {
    name: "Gemini 3.1 Flash Lite",
    owned_by: "google",
    context_window: 1000000,
    max_output: 8192,
    input_price: 0.25,
    output_price: 1.5,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "deepseek/deepseek-chat": {
    name: "DeepSeek V4 Flash Chat",
    owned_by: "deepseek",
    context_window: 1000000,
    max_output: 8192,
    input_price: 0.2,
    output_price: 0.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "deepseek/deepseek-reasoner": {
    name: "DeepSeek V4 Flash Reasoner",
    owned_by: "deepseek",
    context_window: 1000000,
    max_output: 8192,
    input_price: 0.2,
    output_price: 0.4,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "deepseek/deepseek-v4-pro": {
    name: "DeepSeek V4 Pro",
    owned_by: "deepseek",
    context_window: 1048576,
    max_output: 65536,
    input_price: 0.435,
    output_price: 0.87,
    reasoning: true,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "moonshot/kimi-k2.7": {
    name: "Kimi K2.7",
    owned_by: "moonshot",
    context_window: 262144,
    max_output: 65536,
    input_price: 0.95,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "moonshot/kimi-k3": {
    name: "Kimi K3",
    owned_by: "moonshot",
    context_window: 1048576,
    max_output: 65536,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "qwen/qwen3.7-max": {
    name: "Qwen3.7 Max",
    owned_by: "qwen",
    context_window: 1000000,
    max_output: 65536,
    input_price: 1.475,
    output_price: 4.425,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "moonshot/kimi-k2.6": {
    name: "Kimi K2.6",
    owned_by: "moonshot",
    context_window: 262144,
    max_output: 65536,
    input_price: 0.95,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "moonshot/kimi-k2.5": {
    name: "Kimi K2.5",
    owned_by: "moonshot",
    context_window: 262144,
    max_output: 16384,
    input_price: 0.6,
    output_price: 3,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "xai/grok-3": {
    name: "Grok 3",
    owned_by: "xai",
    context_window: 131072,
    max_output: 16384,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-3-mini": {
    name: "Grok 3 Mini",
    owned_by: "xai",
    context_window: 131072,
    max_output: 16384,
    input_price: 0.3,
    output_price: 0.5,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4-fast-reasoning": {
    name: "Grok 4 Fast Reasoning",
    owned_by: "xai",
    context_window: 131072,
    max_output: 16384,
    input_price: 0.2,
    output_price: 0.5,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4-fast-non-reasoning": {
    name: "Grok 4 Fast",
    owned_by: "xai",
    context_window: 131072,
    max_output: 16384,
    input_price: 0.2,
    output_price: 0.5,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4-1-fast-reasoning": {
    name: "Grok 4.1 Fast Reasoning",
    owned_by: "xai",
    context_window: 131072,
    max_output: 16384,
    input_price: 0.2,
    output_price: 0.5,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4-1-fast-non-reasoning": {
    name: "Grok 4.1 Fast",
    owned_by: "xai",
    context_window: 131072,
    max_output: 16384,
    input_price: 0.2,
    output_price: 0.5,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4-0709": {
    name: "Grok 4 (0709)",
    owned_by: "xai",
    context_window: 131072,
    max_output: 16384,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-2-vision": {
    name: "Grok 2 Vision",
    owned_by: "xai",
    context_window: 131072,
    max_output: 16384,
    input_price: 2,
    output_price: 10,
    reasoning: false,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4.20-reasoning": {
    name: "Grok 4.20 Reasoning",
    owned_by: "xai",
    context_window: 2000000,
    max_output: 16384,
    input_price: 2,
    output_price: 6,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4.20-non-reasoning": {
    name: "Grok 4.20",
    owned_by: "xai",
    context_window: 2000000,
    max_output: 16384,
    input_price: 2,
    output_price: 6,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4.20-multi-agent": {
    name: "Grok 4.20 Multi-Agent",
    owned_by: "xai",
    context_window: 2000000,
    max_output: 16384,
    input_price: 2,
    output_price: 6,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "xai/grok-4.3": {
    name: "Grok 4.3",
    owned_by: "xai",
    context_window: 1000000,
    max_output: 16384,
    input_price: 1.5,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "xai/grok-4.5": {
    name: "Grok 4.5",
    owned_by: "xai",
    context_window: 500000,
    max_output: 16384,
    input_price: 2.5,
    output_price: 9,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "xai/grok-build-0.1": {
    name: "Grok Build 0.1",
    owned_by: "xai",
    context_window: 256000,
    max_output: 16384,
    input_price: 1.5,
    output_price: 3,
    reasoning: false,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "minimax/minimax-m3": {
    name: "MiniMax M3",
    owned_by: "minimax",
    context_window: 1048576,
    max_output: 65536,
    input_price: 0.3,
    output_price: 1.2,
    reasoning: true,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "minimax/minimax-m2.7": {
    name: "MiniMax M2.7",
    owned_by: "minimax",
    context_window: 204800,
    max_output: 16384,
    input_price: 0.3,
    output_price: 1.2,
    reasoning: true,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "minimax/minimax-m2.5": {
    name: "MiniMax M2.5",
    owned_by: "minimax",
    context_window: 204800,
    max_output: 16384,
    input_price: 0.3,
    output_price: 1.2,
    reasoning: true,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "free/gpt-oss-120b": {
    name: "[Free] GPT-OSS 120B",
    owned_by: "free",
    context_window: 128000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/gpt-oss-20b": {
    name: "[Free] GPT-OSS 20B",
    owned_by: "free",
    context_window: 128000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/deepseek-v4-flash": {
    name: "[Free] DeepSeek V4 Flash",
    owned_by: "free",
    context_window: 1000000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/qwen3-coder-480b": {
    name: "[Free] Qwen3 Coder 480B",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/glm-4.7": {
    name: "[Free] GLM-4.7",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/llama-4-maverick": {
    name: "[Free] Llama 4 Maverick",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/nemotron-3-nano-omni-30b-a3b-reasoning": {
    name: "[Free] Nemotron 3 Nano Omni",
    owned_by: "free",
    context_window: 256000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: false,
  },
  "free/mistral-large-3-675b": {
    name: "[Free] Mistral Large 3 675B",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/qwen3.5-122b-a10b": {
    name: "[Free] Qwen3.5 122B",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/qwen3-next-80b-a3b-instruct": {
    name: "[Free] Qwen3-Next 80B Instruct",
    owned_by: "free",
    context_window: 262144,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/seed-oss-36b": {
    name: "[Free] Seed-OSS 36B",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/mistral-nemotron": {
    name: "[Free] Mistral Nemotron",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/step-3.7-flash": {
    name: "[Free] StepFun Step 3.7 Flash",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/nemotron-nano-9b-v2": {
    name: "[Free] Nemotron Nano 9B v2",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "free/nemotron-nano-12b-v2-vl": {
    name: "[Free] Nemotron Nano 12B v2 VL",
    owned_by: "free",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: true,
    agentic: false,
    tool_calling: false,
  },
  "zai/glm-5.2": {
    name: "GLM-5.2",
    owned_by: "zai",
    context_window: 1000000,
    max_output: 131072,
    input_price: 1.4,
    output_price: 4.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "zai/glm-5.1": {
    name: "GLM-5.1",
    owned_by: "zai",
    context_window: 200000,
    max_output: 128000,
    input_price: 1.4,
    output_price: 4.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "zai/glm-5": {
    name: "GLM-5",
    owned_by: "zai",
    context_window: 200000,
    max_output: 128000,
    input_price: 0.6,
    output_price: 1.92,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "zai/glm-5-turbo": {
    name: "GLM-5 Turbo",
    owned_by: "zai",
    context_window: 200000,
    max_output: 128000,
    input_price: 1.2,
    output_price: 4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  claude: {
    name: "claude → Claude Sonnet 4.6",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "br-sonnet": {
    name: "br-sonnet → Claude Sonnet 4.6",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  sonnet: {
    name: "sonnet → Claude Sonnet 4.6",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "sonnet-4": {
    name: "sonnet-4 → Claude Sonnet 4.6",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "sonnet-4.6": {
    name: "sonnet-4.6 → Claude Sonnet 4.6",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "sonnet-4-6": {
    name: "sonnet-4-6 → Claude Sonnet 4.6",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "sonnet-5": {
    name: "sonnet-5 → Claude Sonnet 5",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-5": {
    name: "opus-5 → Claude Opus 5",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-5.0": {
    name: "opus-5.0 → Claude Opus 5",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-5-0": {
    name: "opus-5-0 → Claude Opus 5",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "sonnet-4.5": {
    name: "sonnet-4.5 → Claude Sonnet 4.5",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "sonnet-4-5": {
    name: "sonnet-4-5 → Claude Sonnet 4.5",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 64000,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  fable: {
    name: "fable → Claude Opus 4.8",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "fable-5": {
    name: "fable-5 → Claude Opus 4.8",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "fable-5.0": {
    name: "fable-5.0 → Claude Opus 4.8",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  opus: {
    name: "opus → Claude Opus 4.8",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-4": {
    name: "opus-4 → Claude Opus 4.8",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-4.8": {
    name: "opus-4.8 → Claude Opus 4.8",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-4-8": {
    name: "opus-4-8 → Claude Opus 4.8",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-4.7": {
    name: "opus-4.7 → Claude Opus 4.7",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-4-7": {
    name: "opus-4-7 → Claude Opus 4.7",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-4.6": {
    name: "opus-4.6 → Claude Opus 4.6",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "opus-4-6": {
    name: "opus-4-6 → Claude Opus 4.6",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 128000,
    input_price: 5,
    output_price: 25,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  haiku: {
    name: "haiku → Claude Haiku 4.5",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 8192,
    input_price: 1,
    output_price: 5,
    reasoning: false,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  gpt: {
    name: "gpt → GPT-4o",
    owned_by: "blockrun",
    context_window: 128000,
    max_output: 16384,
    input_price: 2.5,
    output_price: 10,
    reasoning: false,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  gpt4: {
    name: "gpt4 → GPT-4o",
    owned_by: "blockrun",
    context_window: 128000,
    max_output: 16384,
    input_price: 2.5,
    output_price: 10,
    reasoning: false,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  gpt5: {
    name: "gpt5 → GPT-5.5",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 128000,
    input_price: 5,
    output_price: 30,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "gpt-5.5": {
    name: "gpt-5.5 → GPT-5.5",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 128000,
    input_price: 5,
    output_price: 30,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "gpt-5.4": {
    name: "gpt-5.4 → GPT-5.4",
    owned_by: "blockrun",
    context_window: 400000,
    max_output: 128000,
    input_price: 2.5,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "gpt-5.4-pro": {
    name: "gpt-5.4-pro → GPT-5.4 Pro",
    owned_by: "blockrun",
    context_window: 400000,
    max_output: 128000,
    input_price: 30,
    output_price: 180,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "gpt-5.4-nano": {
    name: "gpt-5.4-nano → GPT-5.4 Nano",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 32768,
    input_price: 0.2,
    output_price: 1.25,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  nano: {
    name: "nano → GPT-5.4 Nano",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 32768,
    input_price: 0.2,
    output_price: 1.25,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "gpt-5-nano": {
    name: "gpt-5-nano → GPT-5.4 Nano",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 32768,
    input_price: 0.2,
    output_price: 1.25,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  codex: {
    name: "codex → GPT-5.3 Codex",
    owned_by: "blockrun",
    context_window: 400000,
    max_output: 128000,
    input_price: 1.75,
    output_price: 14,
    reasoning: false,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  mini: {
    name: "mini → GPT-4o Mini",
    owned_by: "blockrun",
    context_window: 128000,
    max_output: 16384,
    input_price: 0.15,
    output_price: 0.6,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  o1: {
    name: "o1 → o1",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 100000,
    input_price: 15,
    output_price: 60,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "o1-mini": {
    name: "o1-mini → o4-mini",
    owned_by: "blockrun",
    context_window: 128000,
    max_output: 65536,
    input_price: 1.1,
    output_price: 4.4,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  o3: {
    name: "o3 → o3",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 100000,
    input_price: 2,
    output_price: 8,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "gpt-5.4-mini": {
    name: "gpt-5.4-mini → GPT-5.4 Mini",
    owned_by: "blockrun",
    context_window: 400000,
    max_output: 128000,
    input_price: 0.75,
    output_price: 4.5,
    reasoning: false,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  deepseek: {
    name: "deepseek → DeepSeek V4 Flash Chat",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 8192,
    input_price: 0.2,
    output_price: 0.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "deepseek-chat": {
    name: "deepseek-chat → DeepSeek V4 Flash Chat",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 8192,
    input_price: 0.2,
    output_price: 0.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  reasoner: {
    name: "reasoner → DeepSeek V4 Flash Reasoner",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 8192,
    input_price: 0.2,
    output_price: 0.4,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  kimi: {
    name: "kimi → Kimi K2.7",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 65536,
    input_price: 0.95,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  moonshot: {
    name: "moonshot → Kimi K2.7",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 65536,
    input_price: 0.95,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "kimi-k2": {
    name: "kimi-k2 → Kimi K2.7",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 65536,
    input_price: 0.95,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "kimi-k3": {
    name: "kimi-k3 → Kimi K3",
    owned_by: "blockrun",
    context_window: 1048576,
    max_output: 65536,
    input_price: 3,
    output_price: 15,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "kimi-k2.7": {
    name: "kimi-k2.7 → Kimi K2.7",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 65536,
    input_price: 0.95,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "kimi-k2.6": {
    name: "kimi-k2.6 → Kimi K2.6",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 65536,
    input_price: 0.95,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "kimi-k2.5": {
    name: "kimi-k2.5 → Kimi K2.5",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 16384,
    input_price: 0.6,
    output_price: 3,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  qwen: {
    name: "qwen → Qwen3.7 Max",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 65536,
    input_price: 1.475,
    output_price: 4.425,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "qwen3.7-max": {
    name: "qwen3.7-max → Qwen3.7 Max",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 65536,
    input_price: 1.475,
    output_price: 4.425,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "qwen-3.7-max": {
    name: "qwen-3.7-max → Qwen3.7 Max",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 65536,
    input_price: 1.475,
    output_price: 4.425,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "gemini-3-pro-preview": {
    name: "gemini-3-pro-preview → Gemini 3.1 Pro",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 65536,
    input_price: 2,
    output_price: 12,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  gemini: {
    name: "gemini → Gemini 2.5 Pro",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 65536,
    input_price: 1.25,
    output_price: 10,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  flash: {
    name: "flash → Gemini 2.5 Flash",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 65536,
    input_price: 0.3,
    output_price: 2.5,
    reasoning: false,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "gemini-3.1-pro-preview": {
    name: "gemini-3.1-pro-preview → Gemini 3.1 Pro",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 65536,
    input_price: 2,
    output_price: 12,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "gemini-3.5-flash": {
    name: "gemini-3.5-flash → Gemini 3.5 Flash",
    owned_by: "blockrun",
    context_window: 1048576,
    max_output: 65536,
    input_price: 0.5,
    output_price: 3,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: true,
  },
  "gemini-3.1-flash-lite": {
    name: "gemini-3.1-flash-lite → Gemini 3.1 Flash Lite",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 8192,
    input_price: 0.25,
    output_price: 1.5,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "gemini-2.5-flash-lite": {
    name: "gemini-2.5-flash-lite → Gemini 2.5 Flash Lite",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 65536,
    input_price: 0.1,
    output_price: 0.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  grok: {
    name: "grok → Grok 4.3",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 16384,
    input_price: 1.5,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "grok-4.3": {
    name: "grok-4.3 → Grok 4.3",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 16384,
    input_price: 1.5,
    output_price: 4,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "grok-4.5": {
    name: "grok-4.5 → Grok 4.5",
    owned_by: "blockrun",
    context_window: 500000,
    max_output: 16384,
    input_price: 2.5,
    output_price: 9,
    reasoning: true,
    vision: true,
    agentic: true,
    tool_calling: true,
  },
  "grok-fast": {
    name: "grok-fast → Grok 4 Fast Reasoning",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0.2,
    output_price: 0.5,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "grok-build": {
    name: "grok-build → Grok Build 0.1",
    owned_by: "blockrun",
    context_window: 256000,
    max_output: 16384,
    input_price: 1.5,
    output_price: 3,
    reasoning: false,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "grok-code": {
    name: "grok-code → Grok Build 0.1",
    owned_by: "blockrun",
    context_window: 256000,
    max_output: 16384,
    input_price: 1.5,
    output_price: 3,
    reasoning: false,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "grok-code-fast-1": {
    name: "grok-code-fast-1 → DeepSeek V4 Flash Chat",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 8192,
    input_price: 0.2,
    output_price: 0.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  nvidia: {
    name: "nvidia → [Free] GPT-OSS 120B",
    owned_by: "blockrun",
    context_window: 128000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "gpt-120b": {
    name: "gpt-120b → [Free] GPT-OSS 120B",
    owned_by: "blockrun",
    context_window: 128000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "gpt-20b": {
    name: "gpt-20b → [Free] GPT-OSS 20B",
    owned_by: "blockrun",
    context_window: 128000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "mistral-large": {
    name: "mistral-large → [Free] Mistral Large 3 675B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "mistral-large-3-675b": {
    name: "mistral-large-3-675b → [Free] Mistral Large 3 675B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "qwen3.5-122b": {
    name: "qwen3.5-122b → [Free] Qwen3.5 122B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "qwen3-122b": {
    name: "qwen3-122b → [Free] Qwen3.5 122B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "deepseek-free": {
    name: "deepseek-free → [Free] DeepSeek V4 Flash",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "deepseek-v4-pro": {
    name: "deepseek-v4-pro → [Free] DeepSeek V4 Flash",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "deepseek-v4-flash": {
    name: "deepseek-v4-flash → [Free] DeepSeek V4 Flash",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "v4-pro": {
    name: "v4-pro → [Free] DeepSeek V4 Flash",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "v4-flash": {
    name: "v4-flash → [Free] DeepSeek V4 Flash",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "mistral-free": {
    name: "mistral-free → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "glm-free": {
    name: "glm-free → [Free] Seed-OSS 36B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "llama-free": {
    name: "llama-free → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "qwen-coder": {
    name: "qwen-coder → [Free] Seed-OSS 36B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "qwen-coder-free": {
    name: "qwen-coder-free → [Free] Seed-OSS 36B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "qwen-thinking": {
    name: "qwen-thinking → [Free] Qwen3-Next 80B Instruct",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "qwen3-next": {
    name: "qwen3-next → [Free] Qwen3-Next 80B Instruct",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "qwen3-next-80b": {
    name: "qwen3-next-80b → [Free] Qwen3-Next 80B Instruct",
    owned_by: "blockrun",
    context_window: 262144,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "mistral-small": {
    name: "mistral-small → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "seed-oss": {
    name: "seed-oss → [Free] Seed-OSS 36B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "seed-oss-36b": {
    name: "seed-oss-36b → [Free] Seed-OSS 36B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "coder-free": {
    name: "coder-free → [Free] Seed-OSS 36B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "mistral-nemotron": {
    name: "mistral-nemotron → [Free] Mistral Nemotron",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "step-flash": {
    name: "step-flash → [Free] StepFun Step 3.7 Flash",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "step-3.7-flash": {
    name: "step-3.7-flash → [Free] StepFun Step 3.7 Flash",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-nano-9b": {
    name: "nemotron-nano-9b → [Free] Nemotron Nano 9B v2",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-nano": {
    name: "nemotron-nano → [Free] Nemotron Nano 9B v2",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-nano-vl": {
    name: "nemotron-nano-vl → [Free] Nemotron Nano 12B v2 VL",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: true,
    agentic: false,
    tool_calling: false,
  },
  "nano-vl": {
    name: "nano-vl → [Free] Nemotron Nano 12B v2 VL",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: true,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-omni": {
    name: "nemotron-omni → [Free] Nemotron 3 Nano Omni",
    owned_by: "blockrun",
    context_window: 256000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: false,
  },
  "nano-omni": {
    name: "nano-omni → [Free] Nemotron 3 Nano Omni",
    owned_by: "blockrun",
    context_window: 256000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: false,
  },
  "vision-free": {
    name: "vision-free → [Free] Nemotron 3 Nano Omni",
    owned_by: "blockrun",
    context_window: 256000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: true,
    agentic: false,
    tool_calling: false,
  },
  nemotron: {
    name: "nemotron → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-ultra": {
    name: "nemotron-ultra → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-253b": {
    name: "nemotron-253b → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-super": {
    name: "nemotron-super → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-49b": {
    name: "nemotron-49b → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "nemotron-120b": {
    name: "nemotron-120b → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  devstral: {
    name: "devstral → [Free] Seed-OSS 36B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  "devstral-2": {
    name: "devstral-2 → [Free] Seed-OSS 36B",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  maverick: {
    name: "maverick → [Free] Llama 4 Maverick",
    owned_by: "blockrun",
    context_window: 131072,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: true,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  free: {
    name: "free → [Free] GPT-OSS 120B",
    owned_by: "blockrun",
    context_window: 128000,
    max_output: 16384,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  minimax: {
    name: "minimax → MiniMax M3",
    owned_by: "blockrun",
    context_window: 1048576,
    max_output: 65536,
    input_price: 0.3,
    output_price: 1.2,
    reasoning: true,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "minimax-m3": {
    name: "minimax-m3 → MiniMax M3",
    owned_by: "blockrun",
    context_window: 1048576,
    max_output: 65536,
    input_price: 0.3,
    output_price: 1.2,
    reasoning: true,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "minimax-m2.7": {
    name: "minimax-m2.7 → MiniMax M2.7",
    owned_by: "blockrun",
    context_window: 204800,
    max_output: 16384,
    input_price: 0.3,
    output_price: 1.2,
    reasoning: true,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  "minimax-m2.5": {
    name: "minimax-m2.5 → MiniMax M2.5",
    owned_by: "blockrun",
    context_window: 204800,
    max_output: 16384,
    input_price: 0.3,
    output_price: 1.2,
    reasoning: true,
    vision: false,
    agentic: true,
    tool_calling: true,
  },
  glm: {
    name: "glm → GLM-5.2",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 131072,
    input_price: 1.4,
    output_price: 4.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "glm-5.2": {
    name: "glm-5.2 → GLM-5.2",
    owned_by: "blockrun",
    context_window: 1000000,
    max_output: 131072,
    input_price: 1.4,
    output_price: 4.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "glm-5": {
    name: "glm-5 → GLM-5",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 128000,
    input_price: 0.6,
    output_price: 1.92,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "glm-5.1": {
    name: "glm-5.1 → GLM-5.1",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 128000,
    input_price: 1.4,
    output_price: 4.4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "glm-5-turbo": {
    name: "glm-5-turbo → GLM-5 Turbo",
    owned_by: "blockrun",
    context_window: 200000,
    max_output: 128000,
    input_price: 1.2,
    output_price: 4,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: true,
  },
  "auto-router": {
    name: "auto-router → Auto (Smart Router - Balanced)",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 128000,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
  router: {
    name: "router → Auto (Smart Router - Balanced)",
    owned_by: "blockrun",
    context_window: 1050000,
    max_output: 128000,
    input_price: 0,
    output_price: 0,
    reasoning: false,
    vision: false,
    agentic: false,
    tool_calling: false,
  },
};
